version: '3.8'

services:
  app:
    build: .
    container_name: repsy-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/repsydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    container_name: repsy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: repsydb
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: repsy-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9002:9000"  # Burada portu değiştirdik
      - "9001:9001"
    command: server /data
    volumes:
      - minio-data:/data

volumes:
  minio-data:
